name: Deploy Website
on:
  push:
    branches:
      -main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Jekyll Site 
        uses: helaili/jekyll-action@v2
        with:
          target_path: '_site'
          build_options: '--trace'


      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            cd ${{ secrets.TARGET_DIR }}
            git pull origin main
            sudo systemctl reload apache2

